version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app                     # Loyiha papkasi
      - ./static:/app/static       # Hostdagi static fayllar
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs           # Loglar
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  frontend:
    build:
      context: ./frontend
    command: npm run dev
    env_file:
      - .env
    ports:
      - "3000:8080"
    depends_on:
      - web


volumes:
  postgres_data: