version: "3.9"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: /app/runner.sh
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      target: ${FRONTEND_TARGET:-dev}  # dev (local) yoki serve (production)
    env_file:
      - .env
    ports:
      - "3000:3000"  # local dev port, productionda Nginx 80
    depends_on:
      - web

volumes:
  postgres_data: