# Generated by Django 5.2.6 on 2025-09-03 14:10

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=home.models.hero_image_upload_path,
                    ),
                ),
                ("hero_text", models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Home Content",
                "verbose_name_plural": "Home Contents",
            },
        ),
    ]
