# Generated by Django 5.2.6 on 2025-09-03 13:17

import aboutMe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True, help_text="Short intro about yourself"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload your resume",
                        null=True,
                        upload_to=aboutMe.models.resume_upload_path,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=aboutMe.models.profile_image_upload_path,
                    ),
                ),
            ],
            options={
                "verbose_name": "About Me",
                "verbose_name_plural": "About Me",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=aboutMe.models.skill_image_upload_path,
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Years of experience"
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Proficiency in % (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill / Technology",
                "verbose_name_plural": "Skills / Technologies",
            },
        ),
    ]
