# Generated by Django 5.2.6 on 2025-09-07 20:11

import aboutMe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutMe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Certificate or achievement title", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload certificate image (optional)",
                        null=True,
                        upload_to=aboutMe.models.certificate_upload_path,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to certificate or achievement",
                        null=True,
                    ),
                ),
                (
                    "obtained_year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Year obtained (optional)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certificate / Achievement",
                "verbose_name_plural": "Certificates / Achievements",
                "ordering": ["-obtained_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Job title or position", max_length=200),
                ),
                ("company", models.CharField(help_text="Company name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of responsibilities"
                    ),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(help_text="Start year"),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="End year (optional, leave empty if current)",
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Company or project link (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-start_year", "-end_year"],
            },
        ),
    ]
